version: '3'
services:
  account_microservice:
    build: Dockerfile.account
    volumes: 
      - './users.json:/app/users.json' 
    ports:
      - "8000:8000"
  shop_microservice:
    build: Dockerfile.shop
    volumes:
      - './users.json:/app/users.json'
      - './products.json:/app/products.json'
      - './carts.json:/app/carts.json'
    environment:
      ACCOUNT_MICROSERVICE_URL: "http://account_microservice:8000"
    ports:
      - "8001:8001"
    

  order_microservice:
    build: Dockerfile.order
    volumes:
      - './users.json:/app/users.json'
      - './order.json:/app/order.json'
      - './carts.json:/app/carts.json'
    environment:
      ACCOUNT_MICROSERVICE_URL: "http://account_microservice:8000"
      SHOP_MICROSErVICE_URL: "http://shop_microservice:8001"
    ports:
      - 8002:8002
     





