FROM python:3.10-slim


WORKDIR /app

COPY requirements.txt order.py /app


RUN pip install --no-cache-dir -r requirements.txt


CMD ["uvicorn", "order:app", "0.0.0.0", "--port","8002","--proxy-headers"]



