FROM python:3.10-slim



WORKDIR /app

COPY requirements.txt shop.py /app


RUN pip install --no-cache-dir -r requirements.txt


CMD ["uvicorn", "shop:app", "0.0.0.0", "--port","8001","--proxy-headers"]



